### ISSUE TITLE
Issue with testing IDS rules

### ISSUE THREAD

**Issue by someonehelpplease** [SecurityRiskAdvisors/dredd#2]
Hi!
I can use dredd to successfully test SIEM rules with Sigma and Mordor, but somehow I ran into issues when trying to test IDS rules.
For IDS rules, I used snort3-community.rules, and for PCAPs I used NASHUA.pcap and SCRANTON.pcap.
I ran dredd in a virtualenvironment, and I made sure docker was running successfully. I can successfully use dredd to test SIEM rules, so that means docker does work.
However, when I tried to run `python3 dredd-cli suricata -p ~/dredd/pcap/ -r ~/dredd/ids_rules/`, it returned the following error:
`PermissionError: [Errno 13] Permission denied: '/home/kali/dredd/ids_rules/tmp03pdjg2j.rules'`
It's quite weird because tmp03pdjg2j.rules isn't in my ids_rules folder...but anyways I added sudo to run the dredd command again, and encountered a docker error as follows:
`Traceback (most recent call last):
  File "dredd-cli", line 2, in <module>
    from dredd.cli import cli
  File "/home/kali/dredd/dredd/cli/__init__.py", line 1, in <module>
    from .es import es
  File "/home/kali/dredd/dredd/cli/es.py", line 1, in <module>
    from dredd.backends import DreddES
  File "/home/kali/dredd/dredd/backends/__init__.py", line 1, in <module>
    from .docker import docker_client
  File "/home/kali/dredd/dredd/backends/docker.py", line 1, in <module>
    import docker
ModuleNotFoundError: No module named 'docker'`
This is really weird because docker is working, and it worked for dredd testing SIEM rules...so I don't know why it's not working for IDS rule testing....

Any ideas on how to resolve this issue? Thank you so much!

**Comment by 2XXE-SRA** [comment]
The temp file is expected behavior with Dredd. Dredd creates a temp file to merge the rules files in the supplied directory. These are safe to delete - and should be - if the tool fails unexpectedly. 

If you use sudo with Python in a virtualenv, try using the Python from the virtualenv explicitly. So instead of doing

> sudo python ....

do

> sudo python virtualenv/bin/python

This should resolve issues where Python is reporting that a package is not found even though its installed (in the virtualenv).

**Comment by 2XXE-SRA** [comment]
I haven't heard anything from you on this for a while so I'm going to assume its resolved. I will close the issue for now.
